# Try to find the libzip library
#  LIBZIP_FOUND - system has libzip
#  LIBZIP_INCLUDE_DIR_ZIP - the libzip include directory
#  LIBZIP_INCLUDE_DIR_ZIPCONF - the libzip config include directory
#  LIBZIP_LIBRARY - the libzip library
#  LIBZIP_LIBRARIES - the libzip library and its dependencies

FIND_PATH(LIBZIP_INCLUDE_DIR_ZIP NAMES zip.h PATH_SUFFIXES libzip)
FIND_PATH(LIBZIP_INCLUDE_DIR_ZIPCONF NAMES zipconf.h PATH_SUFFIXES libzip)

SET(_LIBZIP_STATIC_LIBS libzip.a)
SET(_LIBZIP_SHARED_LIBS zip libzip)

IF(USE_STATIC_LIBS)
    FIND_LIBRARY(LIBZIP_LIBRARY NAMES ${_LIBZIP_STATIC_LIBS} ${_LIBZIP_SHARED_LIBS})
ELSE()
    FIND_LIBRARY(LIBZIP_LIBRARY NAMES ${_LIBZIP_SHARED_LIBS} ${_LIBZIP_STATIC_LIBS})
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibZip DEFAULT_MSG 
    LIBZIP_LIBRARY 
    LIBZIP_INCLUDE_DIR_ZIP 
    LIBZIP_INCLUDE_DIR_ZIPCONF)
MARK_AS_ADVANCED(LIBZIP_LIBRARY LIBZIP_INCLUDE_DIR_ZIP LIBZIP_INCLUDE_DIR_ZIPCONF)
