set(CMAKE_CXX_STANDARD 17)

# Warning flags based on compiler
if(MSVC)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    add_definitions(-DNOMINMAX)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    set(WARNS_FLAGS "/W3")
else()
    set(WARNS_FLAGS "-Wall -Wextra -Wno-unused -Wno-unused-parameter -Wno-unused-result")
endif()

# Add framework definitions first
if(FRAMEWORK_GRAPHICS)
    add_definitions(-DFW_GRAPHICS)
endif()

if(FRAMEWORK_SOUND)
    add_definitions(-DFW_SOUND)
endif()

if(FRAMEWORK_NET)
    add_definitions(-DFW_NET)
endif()

if(FRAMEWORK_XML)
    add_definitions(-DFW_XML)
endif()

if(WASM)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${WARNS_FLAGS} ${ARCH_FLAGS} -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_SDL=2 -s USE_BOOST_HEADERS=1 -s USE_PTHREADS=1 -O1")
else()
    if(MSVC)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${WARNS_FLAGS} /EHsc")
        set(CMAKE_CXX_FLAGS_DEBUG "/Od /Zi /RTC1")
        set(CMAKE_CXX_FLAGS_RELEASE "/O2 /Oi /GL")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/O2 /Oi /GL /Zi")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${WARNS_FLAGS} ${ARCH_FLAGS} -pipe")
        set(CMAKE_CXX_FLAGS_COMPILESPEED "-O0")
        set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O1 -g -fno-omit-frame-pointer")
        set(CMAKE_CXX_FLAGS_RELEASE "-O2")
        set(CMAKE_CXX_FLAGS_PERFORMANCE "-Ofast -march=native")
    endif()
endif()

# LTO settings
if(USE_LTO)
    if(MSVC)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GL")
        set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} /LTCG")
        set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /LTCG")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /LTCG")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fwhole-program -flto")
        if(WIN32)
            set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -Wl,-O1,--gc-sections,--sort-common,--relax")
        else()
            set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -Wl,-O1,--gc-sections,--sort-common,--relax,-z,relro")
        endif()
    endif()
endif()

# Platform specific settings
if(USE_STATIC_LIBS AND NOT APPLE)
    if(MSVC)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
        set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
    else()
        set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -static-libgcc -static-libstdc++")
    endif()
endif()

# Platform flags
if(WIN32)
    if(MSVC)
        add_definitions(-DWIN32 -D_WIN32_WINNT=0x0501)
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mthreads")
        set(framework_DEFINITIONS ${framework_DEFINITIONS} -D_WIN32_WINNT=0x0501 -DWIN32)
    endif()
elseif(APPLE)
    set(framework_DEFINITIONS ${framework_DEFINITIONS} -D_REENTRANT)
elseif(NOT WASM)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
    set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -rdynamic -Wl,-rpath,./libs")
endif()
