name: "Build: Windows"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "data/**"
      - "mods/**" 
      - "modules/**"
      - "layouts/**"
      - ".github/workflows/build-windows.yaml"
      - "src/**"
  push:
    branches:
      - master
      - develop
      - fix/cmake
    paths:
      - ".github/workflows/build-windows.yaml"
      - "data/**"
      - "mods/**"
      - "modules/**"
      - "layouts/**"
      - "src/**"

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgTriplet: x86-windows-static
        vcpkgGitCommitId: 389e18e8380daab3884e7dc0710ad7f4a264def6
        vcpkgArguments: >
          boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
          luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl

    - name: Integrate vcpkg
      run: |
        ${{ runner.workspace }}/vcpkg/vcpkg integrate install
        
    - name: Compile otclient_dx
      timeout-minutes: 20
      run: |
        cd vc17
        MSBuild /property:Configuration=DirectX /p:BUILD_REVISION=${{github.run_number}}
        
    - name: Compile otclient_gl
      timeout-minutes: 20
      run: |
        cd vc17
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{github.run_number}}

    - name: Upload binaries
      uses: actions/upload-artifact@main
      with:
        name: Download-binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
        if-no-files-found: error
