name: "Build: Ubuntu"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "data/**"
      - "mods/**" 
      - "modules/**"
      - "layouts/**"
      - ".github/workflows/build-ubuntu.yaml"
      - "src/**"
  push:
    branches:
      - master
      - develop
      - feat/premake
    paths:
      - ".github/workflows/build-ubuntu.yaml"
      - "data/**"
      - "mods/**"
      - "modules/**"
      - "layouts/**"
      - "src/**"

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
  VCPKG_BINARY_SOURCES: 'clear;default,readwrite'
  PREMAKE_VERSION: 5.0.0-beta2

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            buildtype: linux-release
            triplet: x64-linux
            artifact-name: otclient
            packages: >-
              ccache
              freeglut3-dev
              libasound2-dev
              libgl-dev
              libgl1-mesa-dev
              libglu1-mesa-dev
              libglew-dev
              libx11-dev
              libxi-dev
              libxmu-dev
              mesa-common-dev
              xorg-dev
              libxrandr-dev
              libluajit-5.1-dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install OS Dependencies
      if: matrix.packages != ''
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.packages }}

    - name: Switch to gcc-12
      run: |
        sudo apt install gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        sudo update-alternatives --set gcc /usr/bin/gcc-12

    - name: Get vcpkg commit id
      id: vcpkg-step
      run: |
        vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')
        echo "vcpkg commit ID: $vcpkgCommitId"
        echo "vcpkgGitCommitId=$vcpkgCommitId" >> "$GITHUB_OUTPUT"

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}
        vcpkgJsonIgnores: "['**/vcpkg/**', '**/browser/overlay-ports/**']"

    - name: Install vcpkg dependencies
      run: |
        vcpkg install --triplet x64-linux

    - name: Download and setup Premake
      run: |
        mkdir -p tools
        wget https://github.com/premake/premake-core/releases/download/v${{ env.PREMAKE_VERSION }}/premake-${{ env.PREMAKE_VERSION }}-linux.tar.gz -O tools/premake.tar.gz
        cd tools
        tar -xzf premake.tar.gz
        chmod +x premake5
        cd ..

    - name: Generate project files
      run: |
        ./tools/premake5 gmake2

    - name: Build project
      run: |
        make -C build config=release

    - name: Create Client Package
      run: |
        mkdir -p ${{ github.workspace }}/client
        cp -R ${{ github.workspace }}/layouts ${{ github.workspace }}/client/
        cp -R ${{ github.workspace }}/data ${{ github.workspace }}/client/
        cp -R ${{ github.workspace }}/mods ${{ github.workspace }}/client/
        cp -R ${{ github.workspace }}/modules ${{ github.workspace }}/client/
        cp ${{ github.workspace }}/init.lua ${{ github.workspace }}/client/
        cp ${{ github.workspace }}/build/bin/Release/otclient ${{ github.workspace }}/client/
        chmod +x ${{ github.workspace }}/client/otclient

    - name: Create and Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: ${{ github.workspace }}/client