name: Code Testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "mods/**" 
      - "modules/**"
      - "layouts/**"
      - "src/**"
  push:
    branches:
      - master
      - develop
    paths:
      - "mods/**" 
      - "modules/**"
      - "layouts/**"
      - "src/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@main

      # todo: https://github.com/OTAcademy/otclientv8/blob/master/.github/workflows/pr-test.yml
      # todo: https://github.com/opentibiabr/canary/tree/main/tests
      - name: Tests
        run: true
