name: Semantic Release

on:
  workflow_run:
    workflows: [
      'Build: Windows',
      'Build: Ubuntu',
      # 'Build: MacOS'
    ]
    branches: [master, develop]
    types:
      - completed

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download artifacts from Windows build
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: otclient
          path: artifacts/windows
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.repository }}

      # Download artifacts from Ubuntu build
      - name: Download Ubuntu Artifacts
        uses: actions/download-artifact@v4
        with:
          name: otclient
          path: artifacts/linux
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.repository }}

      # Download artifacts from MacOS build
      - name: Download MacOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: client
          path: artifacts/macos
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.repository }}

      # Additional steps to handle the downloaded artifacts
      - name: List downloaded artifacts
        run: ls -R artifacts/
